### PR TITLE
implemented music player

### PR DESCRIPTION
**Pull request by yam101**
Added commands for music player (play, pause, resume, skip, remove, queue, exit). Got rid of join command because it wasn't necessary.

### CODE REVIEW

**Comment by sherwinchiu** [comment]
Task linked: [CU-8686ztj08 Allow discord bot to join a call, kind of as a study buddy to keep you on-track with tasks](https://app.clickup.com/t/8686ztj08)

**Review by georgge293 — APPROVED** [review]
looks good

**Review by sherwinchiu — COMMENTED** [review]
lgtm

**Review by sherwinchiu — APPROVED** [review]
lgtm

**Review by jenniferli8263 — APPROVED** [review]
Looks good

**Pull request merged**
