### PR TITLE
Create create_text_channel.js

### PR DESCRIPTION
**Pull request by Jerryzjx**

### CODE REVIEW

**Comment by sherwinchiu** [comment]
Task linked: [CU-86877tkvu /onboarding command would be clutch](https://app.clickup.com/t/86877tkvu)

**Comment by Jerryzjx** [comment]
added a command to create text channels within the same category of the channel where the command was used. I will also create a separate command where we can create a plain channel without any category.

**Comment by Jerryzjx** [comment]
Also added a command for creating a voice channel in the current category. the only change is the channelType

**Comment by Jerryzjx** [comment]
I'm not sure if there is a direct way for us to archive all channels from the Discord documentation, we could set it to read-only for everyone.

**Review by sherwinchiu — APPROVED** [review]
lgtm!

**Pull request merged**
