### PR TITLE
CU-86873020p-py-js-refactor

### PR DESCRIPTION
**Pull request by J-L0115**
Py to JS refactoring. Adding base template and event handlers.

### CODE REVIEW

**Comment by sherwinchiu** [comment]
Task linked: [CU-86873020p Refactor Python -> JS](https://app.clickup.com/t/86873020p)

**Comment by sherwinchiu** [comment]
Do you know if you can update the readme.md to have local building instructions?

**Comment by carlxw** [comment]
I can write that one up on a separate PR perhaps? We should also add nodemon into our npm modules

**Review by sherwinchiu — APPROVED** [review]
lgtm

**Pull request merged**
